import type { Metadata } from "next";
import localFont from "next/font/local";
import FooterComponent from "../../components/footer";
import "./globals.css";
import "./styles/main.css";
import "./styles/ui.css";
import "./styles/media.css";
import "./styles/pets.css";
import Header from "../../components/header"



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <body>
      <Header/>
      {children}
      <FooterComponent/>
    </body>
  </html>
  );

}
