import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../../components/header";
import HeaderSec from "../../components/headersec";
import Footer from "../../components/footer";
import "./globals.css";
import "./styles/main.css";
import "./styles/ui.css";
import "./styles/media.css";
import "./styles/pets.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerType = "default",
}: Readonly<{
  children: React.ReactNode;
  headerType?: "default" | "secondary";
}>) {
  const HeaderComponent = headerType === "secondary" ? HeaderSec : Header;  
  return (
    <html lang="en">
      <body>
      <HeaderComponent/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
